import sqlite3
import os
import json

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "production_history.db")

fifty_topics = [
    # Shiva Purana
    {"id": "shiva_parvati_vivah", "category": "शिव पुराण", "title": "शिव और पार्वती का अद्भुत विवाह", "keywords": ["शिव-पार्वती", "विवाह", "भूत-पिशाच", "कैलाश"], "prompt": "Tell the story of Lord Shiva's bizarre wedding procession (Baraat) filled with ghosts and goblins, and how Parvati accepted him."},
    {"id": "ganesha_head", "category": "शिव पुराण", "title": "गणेश जी को हाथी का सिर कैसे मिला?", "keywords": ["गणेश", "शिव", "पार्वती", "गजासुर", "हाथी का सिर"], "prompt": "Explain the story of Goddess Parvati creating Ganesha from turmeric, his fight with Lord Shiva, and the placement of the elephant head."},
    {"id": "kartikeya_peacock", "category": "शिव पुराण", "title": "कार्तिकेय और मोर की सवारी", "keywords": ["कार्तिकेय", "मुरुगन", "तारकासुर", "मोर", "शिव"], "prompt": "Tell the story of Lord Kartikeya defeating the demon Surapadman, who then transformed into a peacock to become his eternal vehicle."},
    {"id": "ganga_descent", "category": "शिव पुराण", "title": "गंगा का धरती पर अवतरण", "keywords": ["गंगा", "भगीरथ", "शिव की जटाएं", "तपस्या"], "prompt": "Narrate the story of Bhagiratha's penance and how Lord Shiva caught the mighty river Ganga in his matted hair to prevent the Earth's destruction."},
    {"id": "dadhichi_bones", "category": "शिव पुराण", "title": "महर्षि दधीचि का अस्थि दान", "keywords": ["दधीचि", "वृत्रासुर", "वज्र", "इंद्र", "त्याग"], "prompt": "Tell the story of Sage Dadhichi sacrificing his own life and donating his bones to create the Vajra weapon for Lord Indra to defeat Vritrasura."},
    {"id": "markandeya_mrityunjaya", "category": "शिव पुराण", "title": "मार्कण्डेय और महामृत्युंजय मंत्र", "keywords": ["मार्कण्डेय", "यमराज", "महामृत्युंजय", "शिव भक्ति"], "prompt": "Tell the story of the 16-year-old boy Markandeya who hugged the Shiva Linga to escape Death (Yamaraj), leading Shiva to grant him immortality."},

    # Dashavatar / Vishnu Purana
    {"id": "kurma_avatar", "category": "विष्णु पुराण", "title": "कूर्म अवतार और मंदार पर्वत", "keywords": ["कूर्म अवतार", "समुद्र मंथन", "विष्णु", "मंदार पर्वत"], "prompt": "Explain Lord Vishnu's Kurma (tortoise) avatar, which supported Mount Mandara on its back during the churning of the ocean."},
    {"id": "narasimha_hiranyakashipu", "category": "विष्णु पुराण", "title": "नृसिंह अवतार और प्रह्लाद", "keywords": ["नृसिंह", "हिरण्यकशिपु", "प्रह्लाद", "खंभा", "विष्णु"], "prompt": "Tell the fierce story of Lord Narasimha emerging from a pillar at twilight to kill the demon king Hiranyakashipu and protect his devotee Prahlad."},
    {"id": "vamana_bali", "category": "विष्णु पुराण", "title": "वामन अवतार और राजा बलि", "keywords": ["वामन", "राजा बलि", "तीन पग", "पाताल", "विष्णु"], "prompt": "Narrate the story of the dwarf Brahmin Vamana who asked demon king Mahabali for three paces of land, ultimately measuring the universe."},
    {"id": "parashurama_rage", "category": "विष्णु पुराण", "title": "परशुराम का क्रोध", "keywords": ["परशुराम", "सहस्रार्जुन", "फरसा", "क्षत्रिय", "विष्णु"], "prompt": "Tell the story of Lord Parashurama's vow to rid the earth of arrogant Kshatriya kings after the evil king Kartavirya Arjuna stole his father's divine cow."},
    {"id": "dhruva_star", "category": "विष्णु पुराण", "title": "भक्त ध्रुव और ध्रुव तारा", "keywords": ["भक्त ध्रुव", "तपस्या", "विष्णु", "ध्रुव तारा", "अटल"], "prompt": "Tell the story of the little boy Dhruva who performed severe penance in the forest after being insulted by his stepmother, earning the eternal position of the Pole Star."},
    {"id": "satyavan_savitri", "category": "पौराणिक कथा", "title": "सावित्री और सत्यवान की कथा", "keywords": ["सावित्री", "सत्यवान", "यमराज", "पतिव्रता", "मृत्यु"], "prompt": "Narrate the story of Princess Savitri who followed Yamaraj (the god of death) and debated with him to win back the life of her husband, Satyavan."},

    # Ramayana
    {"id": "sita_swayamvar", "category": "रामायण कथा", "title": "सीता स्वयंवर और शिव धनुष", "keywords": ["सीता स्वयंवर", "राम", "शिव धनुष", "परशुराम", "जनक"], "prompt": "Describe the grand event of Sita Swayamvar where Lord Rama effortlessly lifted and broke Lord Shiva's divine bow, Pinaka."},
    {"id": "ahilya_redemption", "category": "रामायण कथा", "title": "अहिल्या का उद्धार", "keywords": ["अहिल्या", "गौतम ऋषि", "श्राप", "पत्थर", "श्री राम"], "prompt": "Tell the story of Ahilya, who was cursed to become a stone by Sage Gautam, and how she attained liberation through the touch of Lord Rama's feet."},
    {"id": "jatayu_sacrifice", "category": "रामायण कथा", "title": "जटायु का बलिदान", "keywords": ["जटायु", "रावण", "सीता हरण", "श्री राम", "बलिदान"], "prompt": "Narrate the heroic and tragic battle of the old bird Jatayu fighting Ravana in the sky to protect Goddess Sita from abduction."},
    {"id": "kumbhakarna_sleep", "category": "रामायण कथा", "title": "कुंभकर्ण की नींद का रहस्य", "keywords": ["कुंभकर्ण", "निद्रासन", "इंद्रासन", "ब्रह्मा", "रावण"], "prompt": "Explain why Kumbhakarna slept for six months a year. Tell the story of Goddess Saraswati twisting his tongue when he asked Brahma for 'Indrasan' but said 'Nidrasan'."},
    {"id": "ravana_shiva_tandava", "category": "रामायण कथा", "title": "रावण और शिव तांडव स्तोत्र", "keywords": ["रावण", "शिव तांडव", "कैलाश", "महादेव", "अहंकार"], "prompt": "Tell the story of Ravana arrogantly trying to lift Mount Kailash, Lord Shiva pressing it down with his toe, and Ravana singing the Shiva Tandava Stotram in agony and devotion."},
    {"id": "shabari_berries", "category": "रामायण कथा", "title": "शबरी के जूठे बेर", "keywords": ["शबरी", "श्री राम", "भक्ति", "बेर", "मतंग ऋषि"], "prompt": "Narrate the deeply devoted story of Shabari offering pre-tasted, half-eaten berries to Lord Rama to ensure they were sweet, and Rama eating them with love."},
    {"id": "setu_bandhan_squirrel", "category": "रामायण कथा", "title": "राम सेतु और छोटी गिलहरी", "keywords": ["राम सेतु", "गिलहरी", "श्री राम", "वानर सेना", "योगदान"], "prompt": "Tell the sweet story of the little squirrel carrying sand to help build the Ram Setu, and how Lord Rama lovingly stroked its back, leaving the three stripes."},

    # Mahabharata & Krishna Leela
    {"id": "krishna_birth", "category": "कृष्ण लीला", "title": "श्री कृष्ण का जन्म और कारागार", "keywords": ["कृष्ण जन्म", "देवकी", "वासुदेव", "कंस", "यमुना"], "prompt": "Describe the miraculous midnight birth of Lord Krishna in Kansa's prison, the doors magically opening, and Vasudeva carrying him across the raging Yamuna river."},
    {"id": "putana_salvation", "category": "कृष्ण लीला", "title": "पूतना का उद्धार", "keywords": ["पूतना", "कृष्ण", "जहर", "मोक्ष", "गोकुल"], "prompt": "Tell the story of the demoness Putana trying to poison baby Krishna with her milk, but Krishna sucking the life out of her and granting her liberation."},
    {"id": "govardhan_puja", "category": "कृष्ण लीला", "title": "गोवर्धन पर्वत और इंद्र का कोप", "keywords": ["गोवर्धन", "इंद्र", "कृष्ण", "बारिश", "अहंकार"], "prompt": "Narrate the story of little Krishna lifting the massive Govardhan Hill on his pinky finger for seven days to protect the villagers of Vrindavan from Lord Indra's torrential wrath."},
    {"id": "kalia_mardan", "category": "कृष्ण लीला", "title": "कालिया नाग का मर्दन", "keywords": ["कालिया नाग", "यमुना", "कृष्ण", "तांडव", "वृंदावन"], "prompt": "Tell the story of Krishna diving into the poisonous Yamuna river, fighting the multi-headed serpent Kalia, and dancing triumphantly on his hoods."},
    {"id": "sudama_rice", "category": "कृष्ण लीला", "title": "सुदामा के चावल", "keywords": ["सुदामा", "कृष्ण", "मित्रता", "द्वारका", "पोहा"], "prompt": "Tell the heartwarming story of poor Sudama visiting King Krishna in Dwarka with a humble gift of beaten rice, and Krishna blessing him with immense wealth."},
    {"id": "draupadi_swayamvar", "category": "महाभारत रहस्य", "title": "द्रौपदी स्वयंवर और मछली की आंख", "keywords": ["द्रौपदी", "अर्जुन", "स्वयंवर", "मछली की आंख", "धनुष"], "prompt": "Describe the grand Draupadi Swayamvar where Arjuna, disguised as a Brahmin, looked at the reflection in the oil to shoot the eye of the spinning wooden fish."},
    {"id": "draupadi_cheerharan", "category": "महाभारत रहस्य", "title": "द्रौपदी चीरहरण और कृष्ण की कृपा", "keywords": ["द्रौपदी", "चीरहरण", "दुशासन", "कृष्ण", "चमत्कार"], "prompt": "Narrate the tragic Sabha scene of Draupadi's Cheerharan where she surrenders completely to Lord Krishna, who provides her with an unending stream of cloth."},
    {"id": "eklavya_gurudakshina", "category": "महाभारत रहस्य", "title": "एकलव्य की गुरुदक्षिणा", "keywords": ["एकलव्य", "द्रोणाचार्य", "अंगूठा", "धनुर्विद्या", "गुरुभक्ति"], "prompt": "Tell the story of the tribal prince Eklavya who practiced archery before a clay statue of Dronacharya, and sacrificed his right thumb as Gurudakshina."},
    {"id": "bhishma_vow", "category": "महाभारत रहस्य", "title": "भीष्म प्रतिज्ञा", "keywords": ["भीष्म", "देवव्रत", "शांतनु", "सत्यवती", "प्रतिज्ञा"], "prompt": "Tell the story of Prince Devavrata taking the terrible vow of lifelong celibacy and giving up the throne for his father's happiness, earning the name Bhishma."},
    {"id": "shikhandi_secret", "category": "महाभारत रहस्य", "title": "शिखंडी का रहस्य", "keywords": ["शिखंडी", "अम्बा", "भीष्म", "महाभारत", "पुनर्जन्म"], "prompt": "Explain the past life story of Princess Amba, who reincarnated as Shikhandi to become the ultimate cause of Bhishma Pitamah's downfall in the Kurukshetra war."},
    {"id": "ashwatthama_curse", "category": "महाभारत रहस्य", "title": "अश्वत्थामा का श्राप", "keywords": ["अश्वत्थामा", "कृष्ण", "मणि", "ब्रह्मास्त्र", "श्राप"], "prompt": "Tell the dark story of Ashwatthama unleashing the Brahmashirsha astra on Abhimanyu's unborn child, and Lord Krishna cursing him to roam the earth in pain for 3000 years."},
    {"id": "gandhari_curse", "category": "महाभारत रहस्य", "title": "गांधारी का श्री कृष्ण को श्राप", "keywords": ["गांधारी", "महाभारत", "कृष्ण", "यदुवंश", "श्राप"], "prompt": "Narrate the aftermath of the Kurukshetra war where a grieving Gandhari blames Lord Krishna and curses the entire Yadava clan to destroy each other in 36 years."},
    {"id": "karna_wheel", "category": "महाभारत रहस्य", "title": "कर्ण के रथ का पहिया", "keywords": ["कर्ण", "परशुराम का श्राप", "रथ का पहिया", "अर्जुन", "कुरुक्षेत्र"], "prompt": "Tell the story of Karna's final moments when his chariot wheel got stuck in the mud due to a curse, and he forgot his mantras, leading to his defeat."},
    {"id": "yaksha_prashna", "category": "महाभारत रहस्य", "title": "यक्ष प्रश्न और युधिष्ठिर का धर्म", "keywords": ["यक्ष प्रश्न", "युधिष्ठिर", "धर्मराज", "तालाब", "पांडव"], "prompt": "Narrate the story of the magical lake where a Yaksha poisoned four Pandavas for ignoring his warnings, and Yudhishthira revived them by answering profound philosophical questions."},

    # Vedic Astrology / Jyotish
    {"id": "surya_sanjana_chhaya", "category": "ज्योतिष कथा", "title": "सूर्यदेव और छाया का रहस्य", "keywords": ["सूर्य देव", "संजना", "छाया", "शनिदेव", "ज्योतिष"], "prompt": "Tell the Puranic story of Surya's wife Sanjana leaving her shadow clone (Chhaya) behind because she couldn't bear his heat, leading to the birth of Shani Dev."},
    {"id": "chandra_curse", "category": "ज्योतिष कथा", "title": "चंद्रमा को क्षय रोग का श्राप", "keywords": ["चंद्रमा", "दक्ष प्रजापति", "रोहिणी", "श्राप", "सोमनाथ"], "prompt": "Explain the Jyotish mythology of why the Moon waxes and wanes: Daksha's curse on Chandra for favoring only Rohini among his 27 star-wives, and Shiva placing Chandra on his head."},
    {"id": "brihaspati_shukracharya", "category": "ज्योतिष कथा", "title": "देवगुरु बृहस्पति और दैत्यगुरु शुक्राचार्य", "keywords": ["बृहस्पति", "शुक्राचार्य", "देवता", "असुर", "संजीवनी विद्या"], "prompt": "Explain the cosmic rivalry between Jupiter (Guru of Devas) and Venus (Guru of Asuras), and how Shukracharya obtained the Sanjeevani Vidya to resurrect the dead."},
    {"id": "manglik_energy", "category": "ज्योतिष कथा", "title": "मंगल दोष: ऊर्जा या श्राप?", "keywords": ["मंगल दोष", "मांगलिक", "कुजा दोष", "ऊर्जा", "विवाह"], "prompt": "Deep dive into the astrological significance of Mars in the 1st, 4th, 7th, 8th, or 12th house, explaining how Manglik dosha is about excess aggressive energy, not a death sentence."},
    {"id": "budh_tara_birth", "category": "ज्योतिष कथा", "title": "बुध (Mercury) का रहस्यमयी जन्म", "keywords": ["बुध", "चंद्रमा", "तारा", "बृहस्पति", "बुद्धि"], "prompt": "Tell the controversial Jyotish myth of Budh's (Mercury) birth from the illicit union of Chandra (Moon) and Tara (Jupiter's wife), making Mercury the planet of neutral intellect."},
    {"id": "kaal_sarp_dosh", "category": "ज्योतिष कथा", "title": "काल सर्प दोष का असली मतलब", "keywords": ["काल सर्प दोष", "राहु", "केतु", "कुंडली", "कर्म"], "prompt": "Explain the Kaal Sarp Dosh in Vedic Astrology when all 7 planets are trapped between Rahu and Ketu, symbolizing intense past-life karma and extreme life swings."},
    {"id": "pitru_dosh", "category": "ज्योतिष कथा", "title": "पितृ दोष: पूर्वजों का ऋण", "keywords": ["पितृ दोष", "सूर्य", "राहु", "पूर्वज", "श्राद्ध"], "prompt": "Explain the concept of Pitru Dosh (Ancestral affliction) caused by Sun-Rahu conjunctions, representing unfulfilled desires of ancestors and the importance of gratitude."},
    {"id": "guru_chandal_yoga", "category": "ज्योतिष कथा", "title": "गुरु चांडाल योग", "keywords": ["गुरु चांडाल", "बृहस्पति", "राहु", "ज्ञान", "भ्रम"], "prompt": "Explain the dreaded Guru Chandal Yoga formed by Jupiter and Rahu together, showing how the illusion of Rahu corrupts the pure wisdom of Jupiter, leading to moral dilemmas."},
    {"id": "gajakesari_yoga", "category": "ज्योतिष कथा", "title": "गजकेसरी योग: सफलता का राज", "keywords": ["गजकेसरी योग", "बृहस्पति", "चंद्रमा", "राजयोग", "सफलता"], "prompt": "Describe one of the most auspicious yogas in astrology, the Gajakesari Yoga (Elephant-Lion), formed by Jupiter in a Kendra from the Moon, granting wisdom, wealth, and lasting fame."},
    {"id": "kemdrum_dosh", "category": "ज्योतिष कथा", "title": "केमद्रुम दोष: चंद्रमा का अकेलापन", "keywords": ["केमद्रुम दोष", "चंद्रमा", "अकेलापन", "दरिद्रता", "मानसिक शांति"], "prompt": "Explain Kemdrum Dosh, formed when the Moon has no planets on either side in a Kundali, leading to feelings of deep loneliness, mental struggles, and poverty."},

    # Nakshatra Gyaan
    {"id": "ashwini_nakshatra", "category": "नक्षत्र ज्ञान", "title": "अश्विनी कुमार: देवताओं के वैद्य", "keywords": ["अश्विनी नक्षत्र", "अश्विनी कुमार", "केतु", "वैद्य", "हीलिंग"], "prompt": "Explore the first Nakshatra, Ashwini, ruled by Ketu. Tell the story of the Ashwini Kumaras, the twin horse-headed divine physicians who perform miracles and represent fast healing."},
    {"id": "ardra_nakshatra", "category": "नक्षत्र ज्ञान", "title": "आर्द्रा नक्षत्र: शिव का आंसू", "keywords": ["आर्द्रा", "राहु", "रुद्र", "विनाश", "आंसू"], "prompt": "Explain Ardra Nakshatra (ruled by Rahu). Relate it to Lord Rudra, the storm god, symbolizing destruction of the old, tears of sorrow, and the fresh start after a heavy storm."},
    {"id": "pushya_nakshatra", "category": "नक्षत्र ज्ञान", "title": "पुष्य नक्षत्र: सबसे शुभ तारा", "keywords": ["पुष्य नक्षत्र", "बृहस्पति", "शनि", "शुभ", "पोषण"], "prompt": "Describe Pushya Nakshatra, the most nourishing and auspicious star ruled by Saturn but guided by Jupiter. Explain why it is considered the absolute best time for buying gold or starting ventures."},
    {"id": "magha_nakshatra", "category": "नक्षत्र ज्ञान", "title": "मघा नक्षत्र: शाही सिंहासन", "keywords": ["मघा नक्षत्र", "केतु", "पितृ", "राजसी", "पूर्वज"], "prompt": "Explain Magha Nakshatra, the royal throne ruled by Ketu and the Pitris (Ancestors). Discuss its energy of legacy, past-life royal connections, and ancestral blessings."},
    {"id": "mula_nakshatra", "category": "नक्षत्र ज्ञान", "title": "मूल नक्षत्र: विनाश और जड़ें", "keywords": ["मूल नक्षत्र", "केतु", "निरृति", "विनाश", "गहराई"], "prompt": "Dive deep into Mula Nakshatra (The Root), ruled by Goddess Nirriti (destruction). Explain how it strips away illusions, causing pain but forcing spiritual grounding and seeking the core truth."},
    {"id": "revati_nakshatra", "category": "नक्षत्र ज्ञान", "title": "रेवती नक्षत्र: अंतिम यात्रा", "keywords": ["रेवती नक्षत्र", "बुध", "पूषन", "मोक्ष", "अंतिम"], "prompt": "Explore Revati, the 27th and final Nakshatra ruled by Mercury and Pushan. Explain how it represents the final spiritual journey, immense wealth, unconditional love, and the end of karmic cycles."}
]

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

count = 0
for t in fifty_topics:
    cursor.execute("SELECT id FROM topic_catalog WHERE id=?", (t["id"],))
    if not cursor.fetchone():
        keywords_json = json.dumps(t["keywords"], ensure_ascii=False)
        cursor.execute("""
            INSERT INTO topic_catalog (id, category, title, keywords, prompt, source_url, used_count)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (t["id"], t["category"], t["title"], keywords_json, t["prompt"], "batch_50", 0))
        count += 1

conn.commit()
print(f"Inserted {count} new topics for 1 month of content.")
conn.close()
